=== calipho-sib/nextprot-api/user/src/main/resources/db/migration/user.dtd
<!ELEMENT dataset (
   (protein_list_items|
    schema_version|
    user_applications|
    user_protein_lists|
    user_queries|
    user_query_tags|
    user_roles|
    users)*)>

<!ELEMENT protein_list_items EMPTY>
<!ATTLIST protein_list_items
    accession_number CDATA #REQUIRED
    list_id CDATA #REQUIRED
>

<!ELEMENT schema_version EMPTY>
<!ATTLIST schema_version
    version_rank CDATA #REQUIRED
    installed_rank CDATA #REQUIRED
    version CDATA #REQUIRED
    description CDATA #REQUIRED
    type CDATA #REQUIRED
    script CDATA #REQUIRED
    checksum CDATA #IMPLIED
    installed_by CDATA #REQUIRED
    installed_on CDATA #REQUIRED
    execution_time CDATA #REQUIRED
    success CDATA #REQUIRED
>

<!ELEMENT user_applications EMPTY>
<!ATTLIST user_applications
    application_id CDATA #REQUIRED
    application_name CDATA #REQUIRED
    description CDATA #REQUIRED
    organisation CDATA #IMPLIED
    responsible_name CDATA #IMPLIED
    responsible_email CDATA #IMPLIED
    website CDATA #IMPLIED
    owner_id CDATA #IMPLIED
    token CDATA #REQUIRED
    status CDATA #REQUIRED
    user_data_access CDATA #REQUIRED
    origins CDATA #IMPLIED
    creation_date CDATA #REQUIRED
>

<!ELEMENT user_protein_lists EMPTY>
<!ATTLIST user_protein_lists
    list_id CDATA #REQUIRED
    list_name CDATA #IMPLIED
    description CDATA #IMPLIED
    owner_id CDATA #IMPLIED
>

<!ELEMENT user_queries EMPTY>
<!ATTLIST user_queries
    query_id CDATA #REQUIRED
    title CDATA #REQUIRED
    description CDATA #IMPLIED
    sparql CDATA #REQUIRED
    published CDATA #REQUIRED
    owner_id CDATA #IMPLIED
>

<!ELEMENT user_query_tags EMPTY>
<!ATTLIST user_query_tags
    tag_name CDATA #REQUIRED
    query_id CDATA #REQUIRED
>

<!ELEMENT user_roles EMPTY>
<!ATTLIST user_roles
    role_name CDATA #REQUIRED
    user_id CDATA #REQUIRED
>

<!ELEMENT users EMPTY>
<!ATTLIST users
    user_id CDATA #REQUIRED
    user_name CDATA #REQUIRED
    first_name CDATA #IMPLIED
    last_name CDATA #IMPLIED
>

=== calipho-sib/nextprot-api/web/src/test/resources/org/nextprot/api/web/security/UserProteinListControllerIntegrationTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Use this one to run the tests  -->
<!--<!DOCTYPE dataset SYSTEM "https://raw.githubusercontent.com/calipho-sib/nextprot-api/develop/user/src/main/resources/db/migration/user.dtd">-->

<!-- Use this one to autocomplete -->
<!-- <!DOCTYPE dataset SYSTEM "/target/classes/db/migration/user.dtd">-->

<dataset>

    <users user_id="23" user_name="leonard"/>
    <users user_id="24" user_name="sheldon"/>

    <user_protein_lists list_id="157" list_name="leonardslist1" description="my proteins" owner_id="23" public_id="Abc1"/>
    <protein_list_items accession_number="NX_Q14239" list_id="157"/>
    <protein_list_items accession_number="NX_Q8N5Z0" list_id="157"/>
    <protein_list_items accession_number="NX_P05185" list_id="157"/>

    <user_protein_lists list_id="158" list_name="leonardslist2" description="my proteins 2" owner_id="23" public_id="Abc2"/>
    <protein_list_items accession_number="NX_Q14249" list_id="158"/>
    <protein_list_items accession_number="NX_Q8N5Z0" list_id="158"/>
    <protein_list_items accession_number="NX_P05165" list_id="158"/>

</dataset>
