=== calipho-sib/nextprot-api/core/src/main/resources/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="nextprot">
	<xsd:import namespace="nextprot" schemaLocation="nextprot.xsd" />
	<xsd:import namespace="np_mappings" schemaLocation="np_mappings.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="cv_mapping_annotation_types" type="dflt:cv_mapping_annotation_types__type" />
				<xsd:element name="resources" type="dflt:resources__type" />
				<xsd:element name="partnership_resource_assoc_properties" type="dflt:partnership_resource_assoc_properties__type" />
				<xsd:element name="cv_qualifier_types" type="dflt:cv_qualifier_types__type" />
				<xsd:element name="objective_tag_counts" type="dflt:objective_tag_counts__type" />
				<xsd:element name="cv_term_master_view" type="dflt:cv_term_master_view__type" />
				<xsd:element name="gene_identifiers" type="dflt:gene_identifiers__type" />
				<xsd:element name="cv_status" type="dflt:cv_status__type" />
				<xsd:element name="cv_exp_data_identifier_assoc_types" type="dflt:cv_exp_data_identifier_assoc_types__type" />
				<xsd:element name="annotation_relationships" type="dflt:annotation_relationships__type" />
				<xsd:element name="cv_journals" type="dflt:cv_journals__type" />
				<xsd:element name="cv_term_relationship_types" type="dflt:cv_term_relationship_types__type" />
				<xsd:element name="cv_term_categories" type="dflt:cv_term_categories__type" />
				<xsd:element name="cv_program_types" type="dflt:cv_program_types__type" />
				<xsd:element name="cv_term_properties" type="dflt:cv_term_properties__type" />
				<xsd:element name="variants" type="dflt:variants__type" />
				<xsd:element name="cv_date_precisions" type="dflt:cv_date_precisions__type" />
				<xsd:element name="annotation_resource_assoc" type="dflt:annotation_resource_assoc__type" />
				<xsd:element name="identifier_feature_positions" type="dflt:identifier_feature_positions__type" />
				<xsd:element name="cv_synonym_qualifiers" type="dflt:cv_synonym_qualifiers__type" />
				<xsd:element name="dbmaintain_scripts" type="dflt:dbmaintain_scripts__type" />
				<xsd:element name="programs" type="dflt:programs__type" />
				<xsd:element name="mapping_annotations" type="dflt:mapping_annotations__type" />
				<xsd:element name="cv_database_categories" type="dflt:cv_database_categories__type" />
				<xsd:element name="cv_property_types" type="dflt:cv_property_types__type" />
				<xsd:element name="cv_quality_qualifiers" type="dflt:cv_quality_qualifiers__type" />
				<xsd:element name="cv_term_synonyms" type="dflt:cv_term_synonyms__type" />
				<xsd:element name="cv_databases" type="dflt:cv_databases__type" />
				<xsd:element name="cv_term_relationships" type="dflt:cv_term_relationships__type" />
				<xsd:element name="experimental_data_identifier_assoc" type="dflt:experimental_data_identifier_assoc__type" />
				<xsd:element name="resource_properties" type="dflt:resource_properties__type" />
				<xsd:element name="identifier_resource_assoc_properties" type="dflt:identifier_resource_assoc_properties__type" />
				<xsd:element name="expression_view" type="dflt:expression_view__type" />
				<xsd:element name="publications" type="dflt:publications__type" />
				<xsd:element name="experimental_resources" type="dflt:experimental_resources__type" />
				<xsd:element name="cv_terms" type="dflt:cv_terms__type" />
				<xsd:element name="cv_publication_types" type="dflt:cv_publication_types__type" />
				<xsd:element name="identifier_properties" type="dflt:identifier_properties__type" />
				<xsd:element name="view_objective_tags" type="dflt:view_objective_tags__type" />
				<xsd:element name="experiment_properties" type="dflt:experiment_properties__type" />
				<xsd:element name="cv_identifier_types" type="dflt:cv_identifier_types__type" />
				<xsd:element name="objective_tag_relationships" type="dflt:objective_tag_relationships__type" />
				<xsd:element name="identifier_resource_assoc" type="dflt:identifier_resource_assoc__type" />
				<xsd:element name="cv_term_db_xref_assoc" type="dflt:cv_term_db_xref_assoc__type" />
				<xsd:element name="partnership_resource_assoc" type="dflt:partnership_resource_assoc__type" />
				<xsd:element name="partnership_partner_assoc" type="dflt:partnership_partner_assoc__type" />
				<xsd:element name="cv_bio_sequence_types" type="dflt:cv_bio_sequence_types__type" />
				<xsd:element name="protein_feature_positions" type="dflt:protein_feature_positions__type" />
				<xsd:element name="view_master_index" type="dflt:view_master_index__type" />
				<xsd:element name="annotation_resource_assoc_properties" type="dflt:annotation_resource_assoc_properties__type" />
				<xsd:element name="publication_db_xref_assoc" type="dflt:publication_db_xref_assoc__type" />
				<xsd:element name="bio_sequences" type="dflt:bio_sequences__type" />
				<xsd:element name="cv_property_names" type="dflt:cv_property_names__type" />
				<xsd:element name="annotation_properties" type="dflt:annotation_properties__type" />
				<xsd:element name="partnerships" type="dflt:partnerships__type" />
				<xsd:element name="cv_experiment_types" type="dflt:cv_experiment_types__type" />
				<xsd:element name="sequence_identifiers" type="dflt:sequence_identifiers__type" />
				<xsd:element name="experiments" type="dflt:experiments__type" />
				<xsd:element name="data_releases" type="dflt:data_releases__type" />
				<xsd:element name="cv_term_paths" type="dflt:cv_term_paths__type" />
				<xsd:element name="cv_property_values" type="dflt:cv_property_values__type" />
				<xsd:element name="view_master_publication" type="dflt:view_master_publication__type" />
				<xsd:element name="interactions" type="dflt:interactions__type" />
				<xsd:element name="cv_datasources" type="dflt:cv_datasources__type" />
				<xsd:element name="mapping_positions" type="dflt:mapping_positions__type" />
				<xsd:element name="cv_data_releases" type="dflt:cv_data_releases__type" />
				<xsd:element name="pubauthors" type="dflt:pubauthors__type" />
				<xsd:element name="db_xrefs" type="dflt:db_xrefs__type" />
				<xsd:element name="objective_tags" type="dflt:objective_tags__type" />
				<xsd:element name="identifier_synonyms" type="dflt:identifier_synonyms__type" />
				<xsd:element name="master_identifier_name_view" type="dflt:master_identifier_name_view__type" />
				<xsd:element name="cv_experimental_data_types" type="dflt:cv_experimental_data_types__type" />
				<xsd:element name="annotation_protein_assoc" type="dflt:annotation_protein_assoc__type" />
				<xsd:element name="view_cv_term" type="dflt:view_cv_term__type" />
				<xsd:element name="experimental_data_properties" type="dflt:experimental_data_properties__type" />
				<xsd:element name="cv_tag_types" type="dflt:cv_tag_types__type" />
				<xsd:element name="cv_specificity_qualifier_types" type="dflt:cv_specificity_qualifier_types__type" />
				<xsd:element name="publication_view" type="dflt:publication_view__type" />
				<xsd:element name="annotations" type="dflt:annotations__type" />
				<xsd:element name="annotation_synonyms" type="dflt:annotation_synonyms__type" />
				<xsd:element name="cv_resource_assoc_types" type="dflt:cv_resource_assoc_types__type" />
				<xsd:element name="experimental_data" type="dflt:experimental_data__type" />
				<xsd:element name="cv_synonym_types" type="dflt:cv_synonym_types__type" />
				<xsd:element name="cv_resource_types" type="dflt:cv_resource_types__type" />
				<xsd:element name="interaction_identifier_xrefs" type="dflt:interaction_identifier_xrefs__type" />
				<xsd:any namespace="nextprot" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== calipho-sib/nextprot-api/src/test/resources/org/nextprot/api/dao/PtmDaoTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../dbxsd/dataset.xsd">
	
	
	<!-- 
	<sequence_identifiers identifier_id="200" cv_type_id="1" unique_name="NX_P2222" cv_status_id="1" />
	<identifier_synonyms synonym_id="200" identifier_id="200" cv_type_id="1" synonym_name="Protein NUANCE" is_main="true" />
	<view_master_index identifier_id="200" annot_count="1" publication_count="1" />
	<master_identifier_name_view identifier_id="200" unique_name="NX_P2222" gene_name="PAICS" disease="[null]" structure="2345" 
		proteomic="[null]" expression_num="1" mutagenesis_num="[null]" />
	-->	
	<cv_databases cv_id="11" cv_name="Uniprot" description=" ...."/>
	
	
	<!-- CV Terms -->
	
	<cv_terms cv_id="1188" cv_name="glycosylation site" cv_category_id="1" cv_status_id="1"
		db_xref_id="199" />
	<cv_terms cv_id="200" cv_name="Phosphoserine" cv_category_id="16" cv_status_id="1"
		db_xref_id="200" />
	<cv_terms cv_id="201" cv_name="N-linked (GlcNAc...)" cv_category_id="30" cv_status_id="1"
		db_xref_id="201" />
		
		
	<!-- Resource -->
	<resources resource_id="200" cv_type_id="1" />
	<db_xrefs resource_id="200" accession="PTM-204" />

	<resources resource_id="201" cv_type_id="1" />
	<db_xrefs resource_id="201" accession="GLC-204" />
	
	<!-- Sequence Identifiers -->
	<sequence_identifiers identifier_id="10" cv_type_id="1" unique_name="NP_MAS1"
		db_xref_id="100"  cv_status_id="1"/>

	<view_master_index identifier_id="10" annot_count="1" publication_count="1" />
	
	<master_identifier_name_view identifier_id="10" unique_name="NP_MAS1" gene_name="PAICS" disease="1" structure="2345" 
		proteomic="1" expression_num="1" mutagenesis_num="1" />
	
	<resources resource_id="100" cv_type_id="1" />
	<db_xrefs resource_id="100" accession="MAS1" />

	<!-- Isoform -->
	<sequence_identifiers identifier_id="11" cv_type_id="2" unique_name="NP_MAS1-1"
		db_xref_id="3"  cv_status_id="1"/>
	
	<mapping_annotations reference_identifier_id="10" mapped_identifier_id="11"
		cv_type_id="4" />
		
		
	<!-- Annotation -->
	<annotations annotation_id="600" cv_annotation_discriminator_id="13"
		cv_annotation_type_id="13" unique_name="AN_MAS_4" identifier_id="10" description="phosphoserine"
		cv_term_id="200" cv_quality_qualifier_id="50" />
	
	<annotations annotation_id="601" cv_annotation_discriminator_id="13"
		cv_annotation_type_id="1188" unique_name="AN_MAS_5" identifier_id="10" description="glyco"
		cv_term_id="201" cv_quality_qualifier_id="50" />
		
	<annotations annotation_id="602" cv_annotation_discriminator_id="1"
		cv_annotation_type_id="1188" unique_name="AN_MAS_6" identifier_id="10" description="quelque chose avec"
		cv_term_id="201" cv_quality_qualifier_id="50" /> <!-- annotation of not 13 type -->
		
	<!-- Assocs -->
	<annotation_protein_assoc assoc_id="6" annotation_id="600" protein_id="11" />
	<annotation_protein_assoc assoc_id="7" annotation_id="601" protein_id="11" />
<!-- 	<annotation_protein_assoc assoc_id="8" annotation_id="601" protein_id="12" /> -->
<!-- 	<annotation_protein_assoc assoc_id="9" annotation_id="602" protein_id="11" /> -->

	<annotation_resource_assoc annotation_id="600" resource_id="100" cv_qualifier_type_id="4" />
	<annotation_resource_assoc annotation_id="601" resource_id="100" cv_qualifier_type_id="4" />
	<annotation_resource_assoc annotation_id="602" resource_id="100" cv_qualifier_type_id="4" />

	<!-- Position -->
	<protein_feature_positions annotation_protein_id="6" first_pos="100"
		last_pos="101" />
	
	<protein_feature_positions annotation_protein_id="7" first_pos="150"
		last_pos="151" />
	
	<protein_feature_positions annotation_protein_id="8" first_pos="140"
		last_pos="141" />
		
	<protein_feature_positions annotation_protein_id="9" first_pos="1000"
		last_pos="1001" />	

</dataset>

=== calipho-sib/nextprot-api/core/src/test/resources/org/nextprot/api/core/service/DbXrefServiceTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">
	
	<cv_database_categories cv_id="666" cv_name="cat" />
	<cv_databases cv_id="3" cv_name="PubMed" cv_category_id="666" link_url="http://pubmed.com?id=3" url="http://pubmed.com"/>

	<resources resource_id="100" cv_type_id="2"/>
	<publications resource_id="100" title="an interesting paper" text_date="may-2009" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="001eb61d2064031e5c31bd05bb0ef2ed" />
		
	<resources resource_id="110" cv_type_id="1"/>
	<db_xrefs accession="15923218" resource_id="110" cv_database_id="3" />		
	<publication_db_xref_assoc publication_id="100" db_xref_id="110" cv_type_id="1"/>
	
	
	<!--  MASTER -->
	
	<resources resource_id="120" cv_type_id="1"/>
	<db_xrefs accession="789654" resource_id="120" cv_database_id="3"/>
	
	<identifier_resource_assoc resource_id="120" identifier_id="16"/> 
	<sequence_identifiers identifier_id="16" cv_type_id="1" unique_name="NX_P12345"/>
	
	<view_master_identifier_identifiers identifier_name="3D" unique_name="NX_P12345" db_name="Ensembl"/>
	
	
	<!-- PROPERTIES -->
	<resource_properties resource_property_id="500" resource_id="120" property_value="lots" property_name="money" cv_term_value_id="10"/>
	<resource_properties resource_property_id="505" resource_id="120" property_value="squid" property_name="organism name" cv_term_value_id="10"/>
	<resource_properties resource_property_id="501" resource_id="1000" property_value="not much" property_name="something" cv_term_value_id="10"/>
	
</dataset>

=== calipho-sib/nextprot-api/nextprot-api-core/src/test/resources/org/nextprot/api/core/dao/AnnotationMVCTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">

	<sequence_identifiers identifier_id="10" cv_type_id="1" unique_name="NX_P12345" />

	<!-- 	Isoform specificity -->
	<sequence_identifiers identifier_id="11" cv_type_id="2" unique_name="NX_P12345-1" />
	<annotation_protein_assoc annotation_id="10" protein_id="11" assoc_id="10" />
	<protein_feature_positions first_pos="20" last_pos="30" annotation_protein_id="10" position_id="10"/>

	<annotation_protein_assoc annotation_id="11" protein_id="11" assoc_id="11" />
	<protein_feature_positions first_pos="20" last_pos="30" annotation_protein_id="11" position_id="11"/>

	<annotation_protein_assoc annotation_id="12" protein_id="11" assoc_id="12" />
	<protein_feature_positions first_pos="20" last_pos="30" annotation_protein_id="12" position_id="12"/>

	<annotation_protein_assoc annotation_id="13" protein_id="11" assoc_id="13" />
	<protein_feature_positions first_pos="20" last_pos="30" annotation_protein_id="13" position_id="13"/>

	<annotation_protein_assoc annotation_id="14" protein_id="11" assoc_id="14" />
	<protein_feature_positions first_pos="20" last_pos="30" annotation_protein_id="14" position_id="14"/>

	<!-- ontology annotation -->
    <cv_terms cv_id="1301" cv_name="go molecular function" cv_category_id="1" db_xref_id="521" cv_status_id="1" />
    <cv_terms cv_id="1302" cv_name="go biological process" cv_category_id="1" db_xref_id="521" cv_status_id="1" />

	<annotations annotation_id="10" unique_name="AN_P12345_010" identifier_id="10"
		cv_annotation_discriminator_id="3" cv_annotation_type_id="1301" description="AB1 family"
		datasource_id="1" cv_quality_qualifier_id="1" />
		

	<annotations annotation_id="11" unique_name="AN_P12345_011" identifier_id="10"
		cv_annotation_discriminator_id="4" cv_annotation_type_id="1301" description="go function AB1"
		datasource_id="1" cv_quality_qualifier_id="1"/>

	<annotations annotation_id="12" unique_name="AN_P12345_012" identifier_id="10"
		cv_annotation_discriminator_id="3" cv_annotation_type_id="1301"
		description="function with no recognized gene names AB10" datasource_id="1" cv_quality_qualifier_id="1"/>

	<annotations annotation_id="13" unique_name="AN_P12345_013" identifier_id="10"
		cv_annotation_discriminator_id="3" cv_annotation_type_id="1301"
		description="Binds to AB2 and to the complex AB3/AB4." datasource_id="1" cv_quality_qualifier_id="1"/>

	<annotations annotation_id="14" unique_name="AN_P12345_014" identifier_id="10"
		cv_annotation_discriminator_id="3" cv_annotation_type_id="1302" description="Binds to AB1, AB5 and AB4."
		datasource_id="1" cv_quality_qualifier_id="1"/>
		
	<annotation_resource_assoc annotation_id="10" resource_id="10" cv_qualifier_type_id="1" cv_type_id="1"/>
 	<resources resource_id="20"/> 
	<db_xrefs accession="AC_TEST1" resource_id="20" description="some description of an evidence"/>
	
<!-- 	<cv_resource_assoc_types cv_id="1" cv_name="source" description="The resource is the origin of the data (xref on swissprot for master)" /> -->
<!-- 	<cv_resource_assoc_types cv_id="2" cv_name="relative" description="The resource is an information relative to the data (xref on prosite for domain)" /> -->
<!-- 	<cv_resource_assoc_types cv_id="3" cv_name="evidence" description="The resource is an evidence of the data (experimental set for tissue specificity)" /> -->
<!-- 	<cv_resource_assoc_types cv_id="4" cv_name="mapping" description="The resource is equivalent or similar to the original" /> -->
<!-- 	<cv_resource_assoc_types cv_id="5" cv_name="document" description="The resource is the document for the data or the cvterm" /> -->
<!-- 	<cv_resource_assoc_types cv_id="6" cv_name="secondary" description="The resource is a secondary source of the data (secondary acc)" /> -->
	
<!-- 	<cv_resource_assoc_types cv_id="1" cv_name="POTENTIAL" description="There is some logical or conclusive evidence that the given annotation could apply. Often used to present results from protein sequence analysis software tools." /> -->
<!-- 	<cv_resource_assoc_types cv_id="2" cv_name="PROBABLE" description="Stronger evidence than the qualifier ÔPotentialÕ: there must be at least some experimental evidence." /> -->
<!-- 	<cv_resource_assoc_types cv_id="3" cv_name="BY_SIMILARITY" description="Information propagated from other organisms." /> -->
<!-- 	<cv_resource_assoc_types cv_id="4" cv_name="UNKNOWN" description="Not applicable or not known." /> -->
<!-- 	<cv_resource_assoc_types cv_id="5" cv_name="EXP" description="Inferred from Experiment" /> -->
<!-- 	<cv_resource_assoc_types cv_id="6" cv_name="IDA" description="Inferred from Direct Assay" /> -->
<!-- 	<cv_resource_assoc_types cv_id="7" cv_name="IPI" description="Inferred from Physical Interaction" /> -->
<!-- 	<cv_resource_assoc_types cv_id="9" cv_name="IGI" description="Inferred from Genetic Interaction" /> -->
<!-- 	<cv_resource_assoc_types cv_id="10" cv_name="IEP" description="Inferred from Expression Pattern" /> -->
<!-- 	<cv_resource_assoc_types cv_id="11" cv_name="ISS" description="Inferred from Sequence or Structural Similarity" /> -->
<!-- 	<cv_resource_assoc_types cv_id="12" cv_name="ISO" description="Inferred from Sequence Orthology" /> -->
<!-- 	<cv_resource_assoc_types cv_id="13" cv_name="ISA" description="Inferred from Sequence Alignment" /> -->
<!-- 	<cv_resource_assoc_types cv_id="14" cv_name="ISM" description="Inferred from Sequence Model" /> -->
<!-- 	<cv_resource_assoc_types cv_id="15" cv_name="IGC" description="Inferred from Genomic Context" /> -->
<!-- 	<cv_resource_assoc_types cv_id="16" cv_name="RCA" description="Inferred from Reviewed Computational Analysis" /> -->
<!-- 	<cv_resource_assoc_types cv_id="17" cv_name="TAS" description="Traceable Author Statement" /> -->
<!-- 	<cv_resource_assoc_types cv_id="18" cv_name="NAS" description="Non-traceable Author Statement" /> -->
<!-- 	<cv_resource_assoc_types cv_id="19" cv_name="IC" description="Inferred by Curator" /> -->
<!-- 	<cv_resource_assoc_types cv_id="20" cv_name="ND" description="No biological Data available" /> -->
<!-- 	<cv_resource_assoc_types cv_id="21" cv_name="IEA" description="Inferred from Electronic Annotation" /> -->
<!-- 	<cv_resource_assoc_types cv_id="22" cv_name="NR" description="Not Recorded" /> -->
<!-- 	<cv_resource_assoc_types cv_id="8" cv_name="IMP" description="Inferred from Mutant Phenotype" /> -->
<!-- 	<cv_resource_assoc_types cv_id="23" cv_name="IBA" description="Inferred from Biological aspect of Ancestor." /> -->
<!-- 	<cv_resource_assoc_types cv_id="24" cv_name="IBD" description="Inferred from Biological aspect of Descendant." /> -->
<!-- 	<cv_resource_assoc_types cv_id="25" cv_name="IKR" description="Inferred from Key Residues." /> -->
<!-- 	<cv_resource_assoc_types cv_id="26" cv_name="IRD" description="Inferred from Rapid Divergence." /> -->

<!-- 	<cv_resource_assoc_types cv_id="1" cv_name="source" description="The resource is the origin of the data (xref on swissprot for master)" /> -->
<!-- 	<cv_resource_assoc_types cv_id="2" cv_name="relative" description="The resource is an information relative to the data (xref on prosite for domain)" /> -->
<!-- 	<cv_resource_assoc_types cv_id="3" cv_name="evidence" description="The resource is an evidence of the data (experimental set for tissue specificity)" /> -->
<!-- 	<cv_resource_assoc_types cv_id="4" cv_name="mapping" description="The resource is equivalent or similar to the original" /> -->
<!-- 	<cv_resource_assoc_types cv_id="5" cv_name="document" description="The resource is the document for the data or the cvterm" /> -->
<!-- 	<cv_resource_assoc_types cv_id="6" cv_name="secondary" description="The resource is a secondary source of the data (secondary acc)" /> -->
	
</dataset>

=== calipho-sib/nextprot-api/src/test/resources/org/nextprot/api/dao/AntibodyMappingDaoTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">
	
		
	
	<!--  Antibody Master  -->
	<mapping_annotations annotation_id="51" reference_identifier_id="596889" mapped_identifier_id="11" cv_type_id="5" /> 
	
	<!-- 	 Antibody Iso  -->
	<mapping_annotations annotation_id="60" reference_identifier_id="16" mapped_identifier_id="11" cv_type_id="6" /> 
		
	<!--  Iso Master  -->	
	<mapping_annotations annotation_id="70" reference_identifier_id="596889" mapped_identifier_id="16" cv_type_id="4" /> 
	
	<mapping_positions annotation_id="60" position_id="20" first_pos="1" last_pos="1000"/>
	
	<!-- 	ISO 	-->
	<sequence_identifiers identifier_id="16" cv_type_id="1" unique_name="NX_P12345-1"/>

	<!-- 	ANTIBODY 	-->
	<sequence_identifiers identifier_id="11" cv_type_id="6" unique_name="NX_HPA004932" />

	<!-- 	Master 	-->
	<sequence_identifiers identifier_id="596889" cv_type_id="1" unique_name="NX_P12345" db_xref_id="3434634"/>

	
</dataset>

=== calipho-sib/nextprot-api/nextprot-api-core/src/test/resources/org/nextprot/api/core/service/PublicationServiceTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">
	
	<cv_database_categories cv_id="666" cv_name="cat" />
	<cv_databases cv_id="3" cv_name="PubMed" cv_category_id="666"/>
	
	<cv_journals cv_id='100' journal_name="Pretty Revue of Science" iso_abbrev="Pr. Rev. Sc."
		med_abbrev="Pr Rev Sc" issn="0000-0007" essn="[null]"/>
		
	<cv_journals cv_id='101' journal_name="Revue of Science" iso_abbrev="Rev. Sc."
		med_abbrev="Rev Sc" issn="0001-5660" essn="[null]"/>
	
	<!-- 	PUBLICATION 1	 -->
	<resources resource_id="100" cv_type_id="2"/>
	<publications resource_id="100" title="an interesting paper" text_date="may-2009" cv_publication_type_id="10" cv_journal_id="100"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="001eb61d2064031e5c31bd05bb0ef2ed" />
	<pubauthors pubauthor_id="102" publication_id="100" 
		last_name="Luke" fore_name="Lucky" initials="" is_editor="0" rank="0" />		
	<pubauthors pubauthor_id="104" publication_id="100" 
		last_name="Kent" fore_name="Clark" initials="" is_editor="0" rank="1" />
		
	<resources resource_id="110" cv_type_id="1"/>
	<db_xrefs accession="15923218" resource_id="110" cv_database_id="3" />		
	<publication_db_xref_assoc publication_id="100" db_xref_id="110" cv_type_id="1"/>
	
	
	<!-- 	PUBLICATION 2	 -->
	<resources resource_id="101" cv_type_id="2"/>
	<publications resource_id="101" title="an AWESOME paper" text_date="june-2009" cv_publication_type_id="10" cv_journal_id="101"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="001eb61d2064031e5c31bd05bb0ef2ed" />
	<pubauthors pubauthor_id="103" publication_id="101" 
		last_name="Lightyear" fore_name="Buzz" initials="" is_editor="0" rank="0" />		
		
	<resources resource_id="111" cv_type_id="1"/>
	<db_xrefs accession="15923216" resource_id="111" cv_database_id="3" />		
	<publication_db_xref_assoc publication_id="101" db_xref_id="111" cv_type_id="1"/>
	
	<resources resource_id="112" cv_type_id="1"/>
	<db_xrefs accession="15923215" resource_id="112" cv_database_id="3" />		
	<publication_db_xref_assoc publication_id="101" db_xref_id="112" cv_type_id="1"/>
	
	
	<sequence_identifiers identifier_id="100" cv_type_id="1" unique_name="NX_P12345"/>
	<identifier_resource_assoc assoc_id="1" identifier_id="100" resource_id="100" datasource_id="2"/>
	<identifier_resource_assoc assoc_id="2" identifier_id="100" resource_id="101" datasource_id="2"/>
	
</dataset>

=== calipho-sib/nextprot-api/src/test/resources/org/nextprot/api/dao/CvJournalDaoTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">
	
	<cv_journals cv_id='100' journal_name="Pretty Revue of Science" iso_abbrev="Pr. Rev. Sc."
		med_abbrev="Pr Rev Sc" issn="0000-0007" essn="[null]"/>

	<cv_journals cv_id='101' journal_name="Revue of Science" iso_abbrev="Rev. Sc."
		med_abbrev="Rev Sc" issn="0001-5660" essn="[null]"/>
		
	<cv_journals cv_id='102' journal_name="Science signaling" iso_abbrev="Sci Signal"
		med_abbrev="Sci Signal" issn="[null]" essn="0001-566X" />
		
	<resources resource_id="101" cv_type_id="2"/>
	<publications resource_id="101" title="a paper with a title 1" text_date="may-2009" cv_publication_type_id="10" cv_journal_id="100"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="001fbe97e809f51626303615cf4dc6f5"/>
	
	<resources resource_id="102" cv_type_id="2"/>
	<publications resource_id="102" title="a paper with a title 2" text_date="may-2009" cv_publication_type_id="10" cv_journal_id="101"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="002dfcf8f2e9db52367339e3852b308b"/>

	<resources resource_id="103" cv_type_id="2"/>
	<publications resource_id="103" title="a paper with a title 3" text_date="may-2009" cv_publication_type_id="10" cv_journal_id="102"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="002e9f9260c36201b8db79d42469dd4d"/>		
</dataset>
