=== calipho-sib/nextprot-api/core/src/main/resources/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="nextprot">
	<xsd:import namespace="nextprot" schemaLocation="nextprot.xsd" />
	<xsd:import namespace="np_mappings" schemaLocation="np_mappings.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="cv_mapping_annotation_types" type="dflt:cv_mapping_annotation_types__type" />
				<xsd:element name="resources" type="dflt:resources__type" />
				<xsd:element name="partnership_resource_assoc_properties" type="dflt:partnership_resource_assoc_properties__type" />
				<xsd:element name="cv_qualifier_types" type="dflt:cv_qualifier_types__type" />
				<xsd:element name="objective_tag_counts" type="dflt:objective_tag_counts__type" />
				<xsd:element name="cv_term_master_view" type="dflt:cv_term_master_view__type" />
				<xsd:element name="gene_identifiers" type="dflt:gene_identifiers__type" />
				<xsd:element name="cv_status" type="dflt:cv_status__type" />
				<xsd:element name="cv_exp_data_identifier_assoc_types" type="dflt:cv_exp_data_identifier_assoc_types__type" />
				<xsd:element name="annotation_relationships" type="dflt:annotation_relationships__type" />
				<xsd:element name="cv_journals" type="dflt:cv_journals__type" />
				<xsd:element name="cv_term_relationship_types" type="dflt:cv_term_relationship_types__type" />
				<xsd:element name="cv_term_categories" type="dflt:cv_term_categories__type" />
				<xsd:element name="cv_program_types" type="dflt:cv_program_types__type" />
				<xsd:element name="cv_term_properties" type="dflt:cv_term_properties__type" />
				<xsd:element name="variants" type="dflt:variants__type" />
				<xsd:element name="cv_date_precisions" type="dflt:cv_date_precisions__type" />
				<xsd:element name="annotation_resource_assoc" type="dflt:annotation_resource_assoc__type" />
				<xsd:element name="identifier_feature_positions" type="dflt:identifier_feature_positions__type" />
				<xsd:element name="cv_synonym_qualifiers" type="dflt:cv_synonym_qualifiers__type" />
				<xsd:element name="dbmaintain_scripts" type="dflt:dbmaintain_scripts__type" />
				<xsd:element name="programs" type="dflt:programs__type" />
				<xsd:element name="mapping_annotations" type="dflt:mapping_annotations__type" />
				<xsd:element name="cv_database_categories" type="dflt:cv_database_categories__type" />
				<xsd:element name="cv_property_types" type="dflt:cv_property_types__type" />
				<xsd:element name="cv_quality_qualifiers" type="dflt:cv_quality_qualifiers__type" />
				<xsd:element name="cv_term_synonyms" type="dflt:cv_term_synonyms__type" />
				<xsd:element name="cv_databases" type="dflt:cv_databases__type" />
				<xsd:element name="cv_term_relationships" type="dflt:cv_term_relationships__type" />
				<xsd:element name="experimental_data_identifier_assoc" type="dflt:experimental_data_identifier_assoc__type" />
				<xsd:element name="resource_properties" type="dflt:resource_properties__type" />
				<xsd:element name="identifier_resource_assoc_properties" type="dflt:identifier_resource_assoc_properties__type" />
				<xsd:element name="expression_view" type="dflt:expression_view__type" />
				<xsd:element name="publications" type="dflt:publications__type" />
				<xsd:element name="experimental_resources" type="dflt:experimental_resources__type" />
				<xsd:element name="cv_terms" type="dflt:cv_terms__type" />
				<xsd:element name="cv_publication_types" type="dflt:cv_publication_types__type" />
				<xsd:element name="identifier_properties" type="dflt:identifier_properties__type" />
				<xsd:element name="view_objective_tags" type="dflt:view_objective_tags__type" />
				<xsd:element name="experiment_properties" type="dflt:experiment_properties__type" />
				<xsd:element name="cv_identifier_types" type="dflt:cv_identifier_types__type" />
				<xsd:element name="objective_tag_relationships" type="dflt:objective_tag_relationships__type" />
				<xsd:element name="identifier_resource_assoc" type="dflt:identifier_resource_assoc__type" />
				<xsd:element name="cv_term_db_xref_assoc" type="dflt:cv_term_db_xref_assoc__type" />
				<xsd:element name="partnership_resource_assoc" type="dflt:partnership_resource_assoc__type" />
				<xsd:element name="partnership_partner_assoc" type="dflt:partnership_partner_assoc__type" />
				<xsd:element name="cv_bio_sequence_types" type="dflt:cv_bio_sequence_types__type" />
				<xsd:element name="protein_feature_positions" type="dflt:protein_feature_positions__type" />
				<xsd:element name="view_master_index" type="dflt:view_master_index__type" />
				<xsd:element name="annotation_resource_assoc_properties" type="dflt:annotation_resource_assoc_properties__type" />
				<xsd:element name="publication_db_xref_assoc" type="dflt:publication_db_xref_assoc__type" />
				<xsd:element name="bio_sequences" type="dflt:bio_sequences__type" />
				<xsd:element name="cv_property_names" type="dflt:cv_property_names__type" />
				<xsd:element name="annotation_properties" type="dflt:annotation_properties__type" />
				<xsd:element name="partnerships" type="dflt:partnerships__type" />
				<xsd:element name="cv_experiment_types" type="dflt:cv_experiment_types__type" />
				<xsd:element name="sequence_identifiers" type="dflt:sequence_identifiers__type" />
				<xsd:element name="experiments" type="dflt:experiments__type" />
				<xsd:element name="data_releases" type="dflt:data_releases__type" />
				<xsd:element name="cv_term_paths" type="dflt:cv_term_paths__type" />
				<xsd:element name="cv_property_values" type="dflt:cv_property_values__type" />
				<xsd:element name="view_master_publication" type="dflt:view_master_publication__type" />
				<xsd:element name="interactions" type="dflt:interactions__type" />
				<xsd:element name="cv_datasources" type="dflt:cv_datasources__type" />
				<xsd:element name="mapping_positions" type="dflt:mapping_positions__type" />
				<xsd:element name="cv_data_releases" type="dflt:cv_data_releases__type" />
				<xsd:element name="pubauthors" type="dflt:pubauthors__type" />
				<xsd:element name="db_xrefs" type="dflt:db_xrefs__type" />
				<xsd:element name="objective_tags" type="dflt:objective_tags__type" />
				<xsd:element name="identifier_synonyms" type="dflt:identifier_synonyms__type" />
				<xsd:element name="master_identifier_name_view" type="dflt:master_identifier_name_view__type" />
				<xsd:element name="cv_experimental_data_types" type="dflt:cv_experimental_data_types__type" />
				<xsd:element name="annotation_protein_assoc" type="dflt:annotation_protein_assoc__type" />
				<xsd:element name="view_cv_term" type="dflt:view_cv_term__type" />
				<xsd:element name="experimental_data_properties" type="dflt:experimental_data_properties__type" />
				<xsd:element name="cv_tag_types" type="dflt:cv_tag_types__type" />
				<xsd:element name="cv_specificity_qualifier_types" type="dflt:cv_specificity_qualifier_types__type" />
				<xsd:element name="publication_view" type="dflt:publication_view__type" />
				<xsd:element name="annotations" type="dflt:annotations__type" />
				<xsd:element name="annotation_synonyms" type="dflt:annotation_synonyms__type" />
				<xsd:element name="cv_resource_assoc_types" type="dflt:cv_resource_assoc_types__type" />
				<xsd:element name="experimental_data" type="dflt:experimental_data__type" />
				<xsd:element name="cv_synonym_types" type="dflt:cv_synonym_types__type" />
				<xsd:element name="cv_resource_types" type="dflt:cv_resource_types__type" />
				<xsd:element name="interaction_identifier_xrefs" type="dflt:interaction_identifier_xrefs__type" />
				<xsd:any namespace="nextprot" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== calipho-sib/nextprot-api/nextprot-api-core/src/test/resources/org/nextprot/api/core/dao/InteractionTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">
	
	<cv_databases cv_id="143" cv_name="UniProt" description="UniProt web site" />
	<cv_databases cv_id="66" cv_name="IntAct" description="Protein interaction database and analysis system" />
	
	<sequence_identifiers identifier_id="582681" db_xref_id="1052879" cv_type_id="1" unique_name="NX_P51813" cv_status_id="1" />
	<sequence_identifiers identifier_id="1111111" db_xref_id="1111111111" cv_type_id="1" unique_name="NX_Q9NRR5" cv_status_id="1" />
	<db_xrefs resource_id="1052879" accession="P51813" cv_database_id="143"/>
	<db_xrefs resource_id="1111111111" accession="Q9NRR5" cv_database_id="143"/>

	<partnership_partner_assoc assoc_id="87758" db_xref_id="1052879" partnership_id="44171"  is_self_interaction="false"/>
	<partnership_partner_assoc assoc_id="5262" db_xref_id="1052879" partnership_id="2646"  is_self_interaction="false"/>
	<partnership_partner_assoc assoc_id="108957" db_xref_id="1052879" partnership_id="54930"  is_self_interaction="false"/>
	<partnership_partner_assoc assoc_id="19309" db_xref_id="1052879" partnership_id="9714"  is_self_interaction="false"/>
	<partnership_partner_assoc assoc_id="10031" db_xref_id="1052879" partnership_id="5051"  is_self_interaction="false"/>
	<partnership_partner_assoc assoc_id="111111" db_xref_id="1111111111" partnership_id="111112"  is_self_interaction="true"/>
	
	<!-- 	this one is gold -->
	<partnerships partnership_id="44171" cv_quality_qualifier_id="10" cv_status_id="1" datasource_id="100" is_xeno="false"/> 
	<!-- 	those are silver -->
	<partnerships partnership_id="2646" cv_quality_qualifier_id="50" cv_status_id="1" datasource_id="100" is_xeno="false"/>
	<partnerships partnership_id="54930" cv_quality_qualifier_id="50" cv_status_id="1" datasource_id="100" is_xeno="false"/>
	<partnerships partnership_id="9714" cv_quality_qualifier_id="50" cv_status_id="1" datasource_id="100" is_xeno="false"/>
	<partnerships partnership_id="5051" cv_quality_qualifier_id="50" cv_status_id="1" datasource_id="100" is_xeno="false"/>
	<!-- 	this one is related to a fake for self interaction -->
	<partnerships partnership_id="111112" cv_quality_qualifier_id="10" cv_status_id="1" datasource_id="100" is_xeno="false"/> 
	
	<!-- 	Association for number of experiemnts -->
	<!-- 	this one is related to the gold -->
	<partnership_resource_assoc assoc_id="44181" partnership_id="44171" resource_id="15688205"/>
	<!-- 	those are related to the silver -->
	<partnership_resource_assoc assoc_id="2646" partnership_id="2646" resource_id="15645985"/>
	<partnership_resource_assoc assoc_id="61171" partnership_id="54930" resource_id="26526542"/>
	<partnership_resource_assoc assoc_id="9714" partnership_id="9714" resource_id="1052929"/>
	<partnership_resource_assoc assoc_id="5051" partnership_id="5051" resource_id="15648674"/>
	<!-- 	this one is related to a fake for self interaction -->
	<partnership_resource_assoc assoc_id="111114" partnership_id="111112" resource_id="111113"/>
	
	<db_xrefs accession="EBI-696621,EBI-696657" resource_id="15688205" cv_database_id="66"/>
	<db_xrefs accession="EBI-366083,EBI-696657" resource_id="15645985" cv_database_id="66"/>
	<db_xrefs accession="EBI-352572,EBI-696657" resource_id="26526542" cv_database_id="66"/>
	<db_xrefs accession="EBI-696657,EBI-886" resource_id="1052929" cv_database_id="66"/>
	<db_xrefs accession="EBI-3916179,EBI-696657" resource_id="15648674" cv_database_id="66"/>

	<db_xrefs accession="EBI-711226,EBI-711226" resource_id="111113" cv_database_id="66"/>

	<!-- Property name = 5 is related to the number of experiments -->	
	<!-- 	this one is related to the gold -->
	<partnership_resource_assoc_properties assoc_id="44181" cv_property_name_id="5" property_value="4" />
	<!-- 	those are related to the silver -->
	<partnership_resource_assoc_properties assoc_id="2646" cv_property_name_id="5" property_value="1"/>
	<partnership_resource_assoc_properties assoc_id="61171" cv_property_name_id="5" property_value="1"/>
	<partnership_resource_assoc_properties assoc_id="9714" cv_property_name_id="5" property_value="1"/>
	<partnership_resource_assoc_properties assoc_id="5051" cv_property_name_id="5" property_value="1"/>
	<!-- 	this one is related to a fake for self interaction -->
	<partnership_resource_assoc_properties assoc_id="111114" cv_property_name_id="5" property_value="3"/>
	
	
	<!-- 	The other interactants if they exist (left outer join)-->
	<sequence_identifiers identifier_id="619687" db_xref_id="1052931" cv_type_id="1" unique_name="NX_P11309" cv_status_id="1" />
	<sequence_identifiers identifier_id="636519" db_xref_id="970583" cv_type_id="1" unique_name="NX_P04637" cv_status_id="1" />
	<sequence_identifiers identifier_id="618177" db_xref_id="1612287" cv_type_id="1" unique_name="NX_P08238" cv_status_id="1" />
	<sequence_identifiers identifier_id="604714" db_xref_id="960422" cv_type_id="1" unique_name="NX_P46108" cv_status_id="1" />
	<sequence_identifiers identifier_id="641502" db_xref_id="2832372" cv_type_id="1" unique_name="NX_Q8N5I9" cv_status_id="1" />

	<db_xrefs accession="P11309" resource_id="1052931" cv_database_id="143"/>
	<db_xrefs accession="P08238" resource_id="970583" cv_database_id="143"/>
	<db_xrefs accession="P46108" resource_id="1612287" cv_database_id="143"/>
	<db_xrefs accession="P04637" resource_id="960422" cv_database_id="143"/>
	<db_xrefs accession="Q8N5I9" resource_id="2832372" cv_database_id="143"/>

	<partnership_partner_assoc partnership_id="44171" assoc_id="87759" db_xref_id="1052931"/>
	<partnership_partner_assoc partnership_id="2646" assoc_id="5261" db_xref_id="970583"/>
	<partnership_partner_assoc partnership_id="54930" assoc_id="108956" db_xref_id="1612287"/>
	<partnership_partner_assoc partnership_id="9714" assoc_id="19308" db_xref_id="960422"/>
	<partnership_partner_assoc partnership_id="5051" assoc_id="10032" db_xref_id="2832372"/>
	
	
</dataset>

=== calipho-sib/nextprot-api/core/src/test/resources/org/nextprot/api/core/dao/PeptideMappingDaoTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">
	
	<!--  Peptide Master  -->
	<mapping_annotations annotation_id="50" reference_identifier_id="596889" mapped_identifier_id="11" cv_type_id="10" cv_quality_qualifier_id="10"  /> 
	
<!-- 	source_id="" datasource_id="" is_master="" cv_quality_qualifier_id="" /> -->
		
	<!--  Peptide Iso  -->
	<mapping_annotations annotation_id="60" reference_identifier_id="16" mapped_identifier_id="11" cv_type_id="11" /> 
	<!--  source_id="" datasource_id="" is_master="" cv_quality_qualifier_id="" /> -->  
		
	<!--  Iso Master  -->	
	<mapping_annotations annotation_id="70" reference_identifier_id="596889" mapped_identifier_id="16" cv_type_id="4" /> 
	<!-- source_id="" datasource_id="" is_master="" cv_quality_qualifier_id="" /> -->
	
	<mapping_positions annotation_id="60" position_id="20" first_pos="1" last_pos="1000"/>
	
	<!-- 	ISO 	-->
	<sequence_identifiers identifier_id="16" cv_type_id="1" unique_name="NX_P12345-1"/>
	<!-- 	PEPTIDE 	-->
	<sequence_identifiers identifier_id="11" cv_type_id="7" unique_name="NX_PEPT12345678"/>
	
	<!-- 	MASTER -->
	<sequence_identifiers identifier_id="596889" cv_type_id="1" unique_name="NX_P12345"/>
	
	<identifier_properties identifier_property_id="23723875" identifier_id="11" property_value="Y" cv_property_name_id="51" />
	<identifier_properties identifier_property_id="23723876" identifier_id="11" property_value="Y" cv_property_name_id="52" />
	<identifier_properties identifier_property_id="23723877" identifier_id="11" property_value="Y" cv_property_name_id="53" />
	
	<!-- 	EVIDENCES -->
	<cv_database_categories cv_id="666" cv_name="cat" />
	<cv_databases cv_id="3" cv_name="PubMed" cv_category_id="666" link_url="http://pubmed.com?id=3" url="http://pubmed.com"/>
<!-- 	<cv_datasources cv_id="1" cv_name="Ensembl" description="Ensembl database" accession="" url=""/> -->
	
	<resources resource_id="120" cv_type_id="1" />
	<db_xrefs accession="789654" resource_id="120" cv_database_id="3"/>
	<identifier_resource_assoc resource_id="120" identifier_id="11" datasource_id="1"/>
	
</dataset>
