=== calipho-sib/nextprot-api/core/src/main/resources/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="nextprot">
	<xsd:import namespace="nextprot" schemaLocation="nextprot.xsd" />
	<xsd:import namespace="np_mappings" schemaLocation="np_mappings.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="cv_mapping_annotation_types" type="dflt:cv_mapping_annotation_types__type" />
				<xsd:element name="resources" type="dflt:resources__type" />
				<xsd:element name="partnership_resource_assoc_properties" type="dflt:partnership_resource_assoc_properties__type" />
				<xsd:element name="cv_qualifier_types" type="dflt:cv_qualifier_types__type" />
				<xsd:element name="objective_tag_counts" type="dflt:objective_tag_counts__type" />
				<xsd:element name="cv_term_master_view" type="dflt:cv_term_master_view__type" />
				<xsd:element name="gene_identifiers" type="dflt:gene_identifiers__type" />
				<xsd:element name="cv_status" type="dflt:cv_status__type" />
				<xsd:element name="cv_exp_data_identifier_assoc_types" type="dflt:cv_exp_data_identifier_assoc_types__type" />
				<xsd:element name="annotation_relationships" type="dflt:annotation_relationships__type" />
				<xsd:element name="cv_journals" type="dflt:cv_journals__type" />
				<xsd:element name="cv_term_relationship_types" type="dflt:cv_term_relationship_types__type" />
				<xsd:element name="cv_term_categories" type="dflt:cv_term_categories__type" />
				<xsd:element name="cv_program_types" type="dflt:cv_program_types__type" />
				<xsd:element name="cv_term_properties" type="dflt:cv_term_properties__type" />
				<xsd:element name="variants" type="dflt:variants__type" />
				<xsd:element name="cv_date_precisions" type="dflt:cv_date_precisions__type" />
				<xsd:element name="annotation_resource_assoc" type="dflt:annotation_resource_assoc__type" />
				<xsd:element name="identifier_feature_positions" type="dflt:identifier_feature_positions__type" />
				<xsd:element name="cv_synonym_qualifiers" type="dflt:cv_synonym_qualifiers__type" />
				<xsd:element name="dbmaintain_scripts" type="dflt:dbmaintain_scripts__type" />
				<xsd:element name="programs" type="dflt:programs__type" />
				<xsd:element name="mapping_annotations" type="dflt:mapping_annotations__type" />
				<xsd:element name="cv_database_categories" type="dflt:cv_database_categories__type" />
				<xsd:element name="cv_property_types" type="dflt:cv_property_types__type" />
				<xsd:element name="cv_quality_qualifiers" type="dflt:cv_quality_qualifiers__type" />
				<xsd:element name="cv_term_synonyms" type="dflt:cv_term_synonyms__type" />
				<xsd:element name="cv_databases" type="dflt:cv_databases__type" />
				<xsd:element name="cv_term_relationships" type="dflt:cv_term_relationships__type" />
				<xsd:element name="experimental_data_identifier_assoc" type="dflt:experimental_data_identifier_assoc__type" />
				<xsd:element name="resource_properties" type="dflt:resource_properties__type" />
				<xsd:element name="identifier_resource_assoc_properties" type="dflt:identifier_resource_assoc_properties__type" />
				<xsd:element name="expression_view" type="dflt:expression_view__type" />
				<xsd:element name="publications" type="dflt:publications__type" />
				<xsd:element name="experimental_resources" type="dflt:experimental_resources__type" />
				<xsd:element name="cv_terms" type="dflt:cv_terms__type" />
				<xsd:element name="cv_publication_types" type="dflt:cv_publication_types__type" />
				<xsd:element name="identifier_properties" type="dflt:identifier_properties__type" />
				<xsd:element name="view_objective_tags" type="dflt:view_objective_tags__type" />
				<xsd:element name="experiment_properties" type="dflt:experiment_properties__type" />
				<xsd:element name="cv_identifier_types" type="dflt:cv_identifier_types__type" />
				<xsd:element name="objective_tag_relationships" type="dflt:objective_tag_relationships__type" />
				<xsd:element name="identifier_resource_assoc" type="dflt:identifier_resource_assoc__type" />
				<xsd:element name="cv_term_db_xref_assoc" type="dflt:cv_term_db_xref_assoc__type" />
				<xsd:element name="partnership_resource_assoc" type="dflt:partnership_resource_assoc__type" />
				<xsd:element name="partnership_partner_assoc" type="dflt:partnership_partner_assoc__type" />
				<xsd:element name="cv_bio_sequence_types" type="dflt:cv_bio_sequence_types__type" />
				<xsd:element name="protein_feature_positions" type="dflt:protein_feature_positions__type" />
				<xsd:element name="view_master_index" type="dflt:view_master_index__type" />
				<xsd:element name="annotation_resource_assoc_properties" type="dflt:annotation_resource_assoc_properties__type" />
				<xsd:element name="publication_db_xref_assoc" type="dflt:publication_db_xref_assoc__type" />
				<xsd:element name="bio_sequences" type="dflt:bio_sequences__type" />
				<xsd:element name="cv_property_names" type="dflt:cv_property_names__type" />
				<xsd:element name="annotation_properties" type="dflt:annotation_properties__type" />
				<xsd:element name="partnerships" type="dflt:partnerships__type" />
				<xsd:element name="cv_experiment_types" type="dflt:cv_experiment_types__type" />
				<xsd:element name="sequence_identifiers" type="dflt:sequence_identifiers__type" />
				<xsd:element name="experiments" type="dflt:experiments__type" />
				<xsd:element name="data_releases" type="dflt:data_releases__type" />
				<xsd:element name="cv_term_paths" type="dflt:cv_term_paths__type" />
				<xsd:element name="cv_property_values" type="dflt:cv_property_values__type" />
				<xsd:element name="view_master_publication" type="dflt:view_master_publication__type" />
				<xsd:element name="interactions" type="dflt:interactions__type" />
				<xsd:element name="cv_datasources" type="dflt:cv_datasources__type" />
				<xsd:element name="mapping_positions" type="dflt:mapping_positions__type" />
				<xsd:element name="cv_data_releases" type="dflt:cv_data_releases__type" />
				<xsd:element name="pubauthors" type="dflt:pubauthors__type" />
				<xsd:element name="db_xrefs" type="dflt:db_xrefs__type" />
				<xsd:element name="objective_tags" type="dflt:objective_tags__type" />
				<xsd:element name="identifier_synonyms" type="dflt:identifier_synonyms__type" />
				<xsd:element name="master_identifier_name_view" type="dflt:master_identifier_name_view__type" />
				<xsd:element name="cv_experimental_data_types" type="dflt:cv_experimental_data_types__type" />
				<xsd:element name="annotation_protein_assoc" type="dflt:annotation_protein_assoc__type" />
				<xsd:element name="view_cv_term" type="dflt:view_cv_term__type" />
				<xsd:element name="experimental_data_properties" type="dflt:experimental_data_properties__type" />
				<xsd:element name="cv_tag_types" type="dflt:cv_tag_types__type" />
				<xsd:element name="cv_specificity_qualifier_types" type="dflt:cv_specificity_qualifier_types__type" />
				<xsd:element name="publication_view" type="dflt:publication_view__type" />
				<xsd:element name="annotations" type="dflt:annotations__type" />
				<xsd:element name="annotation_synonyms" type="dflt:annotation_synonyms__type" />
				<xsd:element name="cv_resource_assoc_types" type="dflt:cv_resource_assoc_types__type" />
				<xsd:element name="experimental_data" type="dflt:experimental_data__type" />
				<xsd:element name="cv_synonym_types" type="dflt:cv_synonym_types__type" />
				<xsd:element name="cv_resource_types" type="dflt:cv_resource_types__type" />
				<xsd:element name="interaction_identifier_xrefs" type="dflt:interaction_identifier_xrefs__type" />
				<xsd:any namespace="nextprot" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== calipho-sib/nextprot-api/core/src/test/resources/org/nextprot/api/core/service/AntibodyMappingServiceTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">

	<!-- Antibody Masters -->
	<mapping_annotations annotation_id="9547085" reference_identifier_id="636535" mapped_identifier_id="3127922" cv_type_id="5" />
	<mapping_annotations annotation_id="4049518" reference_identifier_id="636535" mapped_identifier_id="1565006" cv_type_id="5" />

	<!-- Antibody Isos  -->
	<mapping_annotations annotation_id="9547084" reference_identifier_id="636537" mapped_identifier_id="3127922" cv_type_id="6" />
	<mapping_annotations annotation_id="9547086" reference_identifier_id="636536" mapped_identifier_id="3127922" cv_type_id="6" />
	<mapping_annotations annotation_id="4049516" reference_identifier_id="636536" mapped_identifier_id="1565006" cv_type_id="6" />
	<mapping_annotations annotation_id="4049517" reference_identifier_id="636537" mapped_identifier_id="1565006" cv_type_id="6" />

	<!-- Iso Master  -->
	<mapping_annotations annotation_id="656672" reference_identifier_id="636535" mapped_identifier_id="636536" cv_type_id="4" />
	<mapping_annotations annotation_id="656673" reference_identifier_id="636535" mapped_identifier_id="636537" cv_type_id="4" />

	<!-- ANTIBODY 	-->
	<sequence_identifiers identifier_id="3127922" cv_type_id="6" unique_name="NX_HPA036303" db_xref_id="39235676" datasource_id="5" />
	<sequence_identifiers identifier_id="1565006" cv_type_id="6" unique_name="NX_HPA036302" db_xref_id="17201575" datasource_id="5" />

	<!-- ISO 	-->
	<sequence_identifiers identifier_id="636536" cv_type_id="2" unique_name="NX_P06213-1"  db_xref_id="2785049" datasource_id="0" />
	<sequence_identifiers identifier_id="636537" cv_type_id="2" unique_name="NX_P06213-2"  db_xref_id="2785050" datasource_id="0" />

	<!-- Positions -->
	<mapping_positions annotation_id="9547084" position_id="10665974" first_pos="245" last_pos="326"/>
	<mapping_positions annotation_id="9547086" position_id="10665977" first_pos="245" last_pos="326"/>
	<mapping_positions annotation_id="4049516" position_id="6199259" first_pos="607" last_pos="742"/>
	<mapping_positions annotation_id="4049517" position_id="6199260" first_pos="607" last_pos="742"/>

	<sequence_identifiers identifier_id="636535" cv_type_id="1" unique_name="NX_P06213" db_xref_id="3434634"  datasource_id="0" />

	<!-- DBXREF -->
	<resources resource_id="120" cv_type_id="1"/>
	<db_xrefs accession="HPA004932" resource_id="120" cv_database_id="3"/>
	
	<!--  irrelevant for antibodies, relevant for peptides ! 
	<identifier_resource_assoc resource_id="120" identifier_id="11"/> 
	-->
	
	<cv_database_categories cv_id="666" cv_name="cat" />
	<cv_databases cv_id="3" cv_name="HPA" cv_category_id="666" link_url="some link" url="some url"/>
</dataset>

=== calipho-sib/nextprot-api/core/src/test/resources/org/nextprot/api/core/dao/AuthorDaoTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">
	
	<resources resource_id="106" cv_type_id="2"/>
	<publications resource_id="106" title="cendrillon" text_date="may-2009" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1234"/>
	<pubauthors pubauthor_id="102" publication_id="106" 
		last_name="Luke" fore_name="Lucky" is_editor="0" rank="1" />
	<pubauthors pubauthor_id="103" publication_id="106" 
		last_name="Montana" fore_name="Toni" initials="T.M." is_editor="0" rank="2"/>		
		
		
	<resources resource_id="107" cv_type_id="2"/>
	<publications resource_id="107" title="what? what?" text_date="june-2010" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1234"/>
	<pubauthors pubauthor_id="104" publication_id="107" 
		last_name="Solo" fore_name="Han" is_editor="0" rank="1" />
</dataset>

=== calipho-sib/nextprot-api/src/test/resources/org/nextprot/api/dao/KeywordDaoTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">
	
	
	
		
	<!-- Keywords 
	
	and prop.property_value in (
	'Biological process', -> KW-1, KW-4
	'Cellular component', -> KW-2
	 'Coding sequence diversity', 'Disease', 'Domain', 'Developmental stage', 'Ligand',
	 'Molecular function', -> KW-3, KW-5
	 
	 'PTM', 'Technical term')
	
	
	-->
	
	
	
	<!-- 	KW-1 	-->
	<cv_terms cv_id="300" cv_name="keyword 1" cv_category_id="13" db_xref_id="102"/>	
	<cv_term_properties cv_term_property_id="300" cv_term_id="300" property_name="Category" property_value="Biological process"/>		
	<resources resource_id="102" cv_type_id="1"/>
	<db_xrefs accession="KW-1" resource_id="102" cv_database_id="13" version="build_53"/>
	
	<!-- 	KW-2 	-->
	<cv_terms cv_id="301" cv_name="keyword 2" cv_category_id="13" db_xref_id="103"/>	
	<cv_term_properties cv_term_property_id="301" cv_term_id="301" property_name="Category" property_value="Cellular component"/>
	<resources resource_id="103" cv_type_id="1"/>
	<db_xrefs accession="KW-2" resource_id="103" cv_database_id="13" version="build_53"/>


	<!-- 	KW-3 	-->
	<cv_terms cv_id="302" cv_name="keyword 3" cv_category_id="13" db_xref_id="104"/>	
	<cv_term_properties cv_term_property_id="302" cv_term_id="302" property_name="Category" property_value="Molecular function"/>	
	<resources resource_id="104" cv_type_id="1"/>
	<db_xrefs accession="KW-3" resource_id="104" cv_database_id="13" version="build_53"/>		

	<!-- 	KW-4 with missing resources & db_xrefs preventing query to retrieve it 	-->
	<cv_terms cv_id="303" cv_name="keyword 4" cv_category_id="13"/>	
	<cv_term_properties cv_term_property_id="303" cv_term_id="303" property_name="Category" property_value="Biological process"/>

	<!-- 	KW-5 with missing resources & db_xrefs preventing query to retrieve it 	-->
	<cv_terms cv_id="304" cv_name="keyword 5" cv_category_id="13"/>	
	<cv_term_properties cv_term_property_id="304" cv_term_id="304" property_name="Category" property_value="Molecular function"/>

	<!-- family -->
	<cv_terms cv_id="400" cv_name="family 1" cv_category_id="22"/>	
	<cv_term_properties cv_term_property_id="400" cv_term_id="400"
		property_name="Category" property_value="Cellular component"/>

	<!-- master -->
	<sequence_identifiers identifier_id="10" cv_type_id="1" unique_name="NX_P12345"/>
	<annotations annotation_id="10" identifier_id="10" cv_term_id="300"/> <!-- KW 1 -->
	<annotations annotation_id="11" identifier_id="10" cv_term_id="301"/> <!-- KW 2 -->
	<annotations annotation_id="12" identifier_id="10" cv_term_id="302"/> <!-- KW 3 -->
	<annotations annotation_id="13" identifier_id="10" cv_term_id="304"/> <!-- KW 5 -->
	<annotations annotation_id="14" identifier_id="10" cv_term_id="400"/> <!-- FAMILY-->		
	
</dataset>

=== calipho-sib/nextprot-api/web/src/test/resources/org/nextprot/api/controller/DbXrefControllerTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">
	
	<!--  PUB  -->
	
	<cv_database_categories cv_id="666" cv_name="cat" />
	<cv_databases cv_id="3" cv_name="PubMed" cv_category_id="666" link_url="http://pubmed.com?id=3" url="http://pubmed.com"/>

	<resources resource_id="100" cv_type_id="2"/>
	<publications resource_id="100" title="an interesting paper" text_date="may-2009" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="001eb61d2064031e5c31bd05bb0ef2ed" />
		
	<resources resource_id="110" cv_type_id="1"/>
	<db_xrefs accession="15923218" resource_id="110" cv_database_id="3" />		
	<publication_db_xref_assoc publication_id="100" db_xref_id="110" cv_type_id="1"/>
	
	<resource_properties resource_property_id="1" resource_id="110" property_name="type" property_value="mutation id" cv_term_value_id="1"/>
	
	
	<!--  MASTER -->
	
	<resources resource_id="120" cv_type_id="1"/>
	<db_xrefs accession="789654" resource_id="120" cv_database_id="3"/>
	
	<resource_properties resource_property_id="2" resource_id="120" property_name="type" property_value="whatever id" cv_term_value_id="2"/>
	
	<identifier_resource_assoc resource_id="120" identifier_id="16"/> 
	<sequence_identifiers identifier_id="16" cv_type_id="1" unique_name="NX_P12345"/>
	
	<!-- VIEW -->
	
	<cv_databases cv_id="7" cv_name="Ensembl" cv_category_id="666" link_url="http://ensembl.com?id=7" url="http://ensembl.com"/>
	<resources resource_id="130" cv_type_id="1"/>
	<db_xrefs accession="3D" resource_id="130" cv_database_id="7"/>
	<view_master_identifier_identifiers identifier_name="3D" unique_name="NX_P12345" db_name="Ensembl"/>
	
	<!-- ANNOTATION -->
	
	<annotations annotation_id="1000" cv_annotation_discriminator_id="3" cv_annotation_type_id="1166" unique_name="AN_123_1"
		description="Receptor for whatever" identifier_id="16" />
		
	<annotation_resource_assoc assoc_id="1" annotation_id="1000" resource_id="4000" cv_qualifier_type_id="4"/>
	
	<cv_databases cv_id="5" cv_name="Cosmic" cv_category_id="666" link_url="http://cosmic.com?id=5" url="http://cosmic.com"/>
	<resources resource_id="4000" cv_type_id="1"/>
	<db_xrefs accession="333" resource_id="4000" cv_database_id="5"/>
	
	
		
</dataset>

=== calipho-sib/nextprot-api/core/src/test/resources/org/nextprot/api/core/dao/PublicationDaoTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">
	
	
	<cv_databases  cv_id="3" cv_name="PubMed"/>
	
	<cv_terms cv_id="30" cv_name="allergen"/>
	<cv_terms cv_id="31" cv_name="family name"/>
	<cv_terms cv_id="32" cv_name="domain"/>
	
	<resources resource_id="100" cv_type_id="2"/>
	<publications resource_id="100" title="an interesting paper" text_date="may-2009" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="001eb61d2064031e5c31bd05bb0ef2ed" />

	<resources resource_id="110" cv_type_id="1"/>
	<db_xrefs accession="15923218" resource_id="110" cv_database_id="3" />		
	<publication_db_xref_assoc publication_id="100" db_xref_id="110" cv_type_id="1"/>

	<resources resource_id="111" cv_type_id="1"/>
	<db_xrefs accession="15923219" resource_id="111" cv_database_id="3" />		
	<publication_db_xref_assoc publication_id="100" db_xref_id="111" cv_type_id="5"/>

	<!-- find by title -->
	<resources resource_id="101" cv_type_id="2"/>
	<publications resource_id="101" title="a paper with a title 1" text_date="may-2009" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="001fbe97e809f51626303615cf4dc6f5"/>

	<resources resource_id="102" cv_type_id="2"/>
	<publications resource_id="102" title="a paper with a title 2" text_date="may-2009" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="002dfcf8f2e9db52367339e3852b308b"/>

	<resources resource_id="103" cv_type_id="2"/>
	<publications resource_id="103" title="a paper with a title 3" text_date="may-2009" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="002e9f9260c36201b8db79d42469dd4d"/>

	<resources resource_id="104" cv_type_id="2"/>
	<publications resource_id="104" title="a paper with a title 4" text_date="may-2009" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1233"/>

	<resources resource_id="105" cv_type_id="2"/>
	<publications resource_id="105" title="cendrillon" text_date="may-2009" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1234"/>
	<pubauthors pubauthor_id="100" publication_id="105" 
		last_name="Dalton" fore_name="Joe" initials="" is_editor="0" rank="0" />
	<pubauthors pubauthor_id="101" publication_id="105" 
		last_name="Dalton" fore_name="Jack" initials="" is_editor="0" rank="1" />
	
	
	<resources resource_id="106" cv_type_id="2"/>
	<publications resource_id="106" title="cendrillon" text_date="may-2009" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1234"/>
	<pubauthors pubauthor_id="102" publication_id="106" 
		last_name="Luke" fore_name="Lucky" initials="" is_editor="0" rank="0" />
	
	<!--  idem 106, but with different text date -->
	<resources resource_id="107" cv_type_id="2"/>
	<publications resource_id="107" title="cendrillon" text_date="may-2010" cv_publication_type_id="10"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1236"/>
	<pubauthors pubauthor_id="103" publication_id="107" 
		last_name="Luke" fore_name="Lucky" initials="" is_editor="0" rank="0" />
	
	<!--  idem 106, but with different type -->
	<resources resource_id="108" cv_type_id="2"/>
	<publications resource_id="108" title="cendrillon" text_date="may-2009" cv_publication_type_id="50"
		datasource_id="4" 
		cv_date_precision_id="30" publication_date="2009-05-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1237"/>
	<pubauthors pubauthor_id="104" publication_id="108" 
		last_name="Luke" fore_name="Lucky" initials="" is_editor="0" rank="0" />


	<!-- Publications linked to identifiers -->
	
	<resources resource_id="301" cv_type_id="2"/>
	<publications title="directly to master" resource_id="301"
		cv_publication_type_id="10" datasource_id="4" 
		text_date="1998" cv_date_precision_id="60" publication_date="1998-01-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1238"/>

	<resources resource_id="310" cv_type_id="1"/>
	<db_xrefs accession="31023218" resource_id="310" cv_database_id="3" />	
	<publication_db_xref_assoc publication_id="301" db_xref_id="310" cv_type_id="1"/>
		
	<resources resource_id="302" cv_type_id="2"/>
	<publications title="directly to master and annotation" resource_id="302"
		cv_publication_type_id="10" datasource_id="4" 
		text_date="1997" cv_date_precision_id="60" publication_date="1997-01-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1239"/>

	<resources resource_id="303" cv_type_id="2"/>
	<publications title="only through annotation" resource_id="303"
		cv_publication_type_id="10" datasource_id="4" 
		text_date="2001" cv_date_precision_id="60" publication_date="2001-01-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1240"/>

	<resources resource_id="304" cv_type_id="2"/>
	<publications title="a patent" resource_id="304"
		cv_publication_type_id="20" datasource_id="2" 
		text_date="2001" cv_date_precision_id="60" publication_date="2001-01-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1241"/>

	<resources resource_id="305" cv_type_id="2"/>
	<publications title="an go article" resource_id="305"
		cv_publication_type_id="10" datasource_id="4" 
		text_date="2008" cv_date_precision_id="60" publication_date="2008-01-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1242"/>

	<resources resource_id="306" cv_type_id="2"/>
	<publications title="an addref article" resource_id="306"
		cv_publication_type_id="10" datasource_id="4" 
		text_date="2007" cv_date_precision_id="60" publication_date="2007-01-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1242"/>

	<resources resource_id="307" cv_type_id="2"/>
	<publications title="an article only linked to annotations" resource_id="307"
		cv_publication_type_id="10" datasource_id="4" 
		text_date="2011" cv_date_precision_id="60" publication_date="2011-01-01 00:00:00" md5="002eec8d3752883c13ab9a1b064c1242"/>

	<sequence_identifiers identifier_id="100" cv_type_id="1" unique_name="NP_MAS1"/>
	<annotations annotation_id="501" identifier_id="100" cv_annotation_discriminator_id="3" unique_name="AN_MAS1_1"
		cv_annotation_type_id="30"/>
	<annotations annotation_id="502" identifier_id="100" cv_annotation_discriminator_id="3" unique_name="AN_MAS1_2"
		cv_annotation_type_id="31"/>
		
	<annotation_resource_assoc annotation_id="501" resource_id="302"/>
	<annotation_resource_assoc annotation_id="501" resource_id="303"/>
	<annotation_resource_assoc annotation_id="502" resource_id="302"/>
	<annotation_resource_assoc annotation_id="502" resource_id="307"/>
	
	<identifier_resource_assoc assoc_id="1" identifier_id="100" resource_id="301" datasource_id="2"/>
	<identifier_resource_assoc assoc_id="2" identifier_id="100" resource_id="302" datasource_id="2"/>
	<identifier_resource_assoc assoc_id="3" identifier_id="100" resource_id="304" datasource_id="2"/>
	<identifier_resource_assoc assoc_id="4" identifier_id="100" resource_id="305" datasource_id="13"/>
	<identifier_resource_assoc assoc_id="5" identifier_id="100" resource_id="301" datasource_id="9"/>  <!-- PIR datasource -->
	<identifier_resource_assoc assoc_id="6" identifier_id="100" resource_id="306" datasource_id="9"/>  <!-- PIR datasource only for this pub -->

	<view_master_publication_assoc pub_id="301" entry_id="100" pf_largescale="0" pf_cited="0" pf_uncited="1" pub_type_id="10" />
	<view_master_publication_assoc pub_id="302" entry_id="100" pf_largescale="0" pf_cited="1" pf_uncited="0" pub_type_id="10" />
	<view_master_publication_assoc pub_id="303" entry_id="100" pf_largescale="0" pf_cited="1" pf_uncited="0" pub_type_id="10" />
	<view_master_publication_assoc pub_id="304" entry_id="100" pf_largescale="0" pf_cited="0" pf_uncited="1" pub_type_id="10" />
	<view_master_publication_assoc pub_id="305" entry_id="100" pf_largescale="0" pf_cited="0" pf_uncited="1" pub_type_id="10" />
	<view_master_publication_assoc pub_id="306" entry_id="100" pf_largescale="0" pf_cited="0" pf_uncited="1" pub_type_id="10" />
	<view_master_publication_assoc pub_id="307" entry_id="100" pf_largescale="0" pf_cited="1" pf_uncited="0" pub_type_id="10" />

</dataset>

=== calipho-sib/nextprot-api/core/src/test/resources/org/nextprot/api/core/dao/FamilyDaoTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../../../../com.genebio.nextprot.datamodel/src/main/resources/dbxsd/dataset.xsd">
	
	
	<sequence_identifiers identifier_id="123" cv_type_id="1" cv_status_id="1" unique_name="OLIV"/>
	
	<cv_databases cv_id="10" cv_name="database" cv_category_id="16" />

	<annotations annotation_id="123" unique_name="SP_007_001" identifier_id="123" cv_annotation_discriminator_id="3"  
		datasource_id="1" cv_annotation_type_id="1059" cv_term_id="200"/>

	<cv_terms cv_id="200" db_xref_id="1000" cv_name="Rothschild"/>
	
	<annotation_properties annotation_property_id="123" annotation_id="123" property_name="family region" property_value="what?"/>

	<resources resource_id="1000" cv_type_id="1" />
	<db_xrefs resource_id="1000" accession="SP_007" cv_database_id="10" />

</dataset>
